second commit
EvgenijLipst/shopping-list pull request #1
Opened 2022-08-27 15:29 UTC by EvgenijLipst

I added actions of menu buttons

2022-08-27 16:53 UTC, evl-alex requested changes

2022-08-27 16:53 UTC, evl-alex commented on src/UI/Board/Select/SelectProducts/index.jsx
> +  const selector = useSelector(state => state.menuReducer);
selectedCategory

2022-08-27 16:53 UTC, evl-alex commented on src/UI/Board/Select/SelectProducts/index.jsx
>          id="combo-box-demo"
probably could be removed

2022-08-27 16:53 UTC, evl-alex commented on src/UI/Board/Select/SelectProducts/index.jsx
> +      <StyledImg src={changeProducts[0].image} alt={"image"} />
will be selectedCategory.image (or your naming)

2022-08-27 16:53 UTC, evl-alex commented on src/UI/Board/index.jsx
> +  const select = selector.title;
pls rename (i.e. selectedCategory)

2022-09-05 10:37 UTC, evl-alex requested changes

2022-09-07 04:50 UTC, evl-alex commented on src/UI/Board/Select/SelectProductOptions/index.jsx
> +          options={weightList}
good naming

2022-09-07 04:51 UTC, evl-alex commented on src/UI/Board/Select/SelectProductOptions/styled.js
> +  border-radius: 0.5em;
going to em's instead of px is good decision

2022-09-07 05:24 UTC, evl-alex commented on src/UI/Board/Select/SelectProducts/index.jsx
> +  }, [productsInfo]);
good, it's correct usage of useMemo hook

2022-09-07 05:24 UTC, evl-alex commented on src/UI/ButtonDeleteAll/index.jsx
> +        // onClick={() => dispatch(addCheckbox(props.title, props.options))}
probably we do want some action on this button)

2022-09-07 05:24 UTC, evl-alex commented on src/UI/Header/index.jsx
> +              key={Math.random()}
Please never use Math.random() as a key). Key should be unique constant value. Perfect candidate is "id" of the item. As we don't have id, we could use name instead. In worst case scenario - item's array index

2022-09-07 05:24 UTC, evl-alex commented on src/features/menu-slice.js
> +  initialState: { title: groceryList, toggle: true },
not very good naming, you store there category / product list / selected category. "Title" makes you think that we have string with some title there

2022-09-07 09:44 UTC, EvgenijLipst commented on src/UI/ButtonDeleteAll/index.jsx
> +        // onClick={() => dispatch(addCheckbox(props.title, props.options))}
This functional just in development now))

2022-09-07 18:11 UTC, merged